// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Ironberg is an autogenerated mock type for the Ironberg type
type Ironberg struct {
	mock.Mock
}

// String provides a mock function with given fields:
func (_m *Ironberg) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIronberg interface {
	mock.TestingT
	Cleanup(func())
}

// NewIronberg creates a new instance of Ironberg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIronberg(t mockConstructorTestingTNewIronberg) *Ironberg {
	mock := &Ironberg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
